Skeleton\Domain\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
  properties:
    username:
      - NotBlank: ~
      - Length: { min: 2, max: 36 }
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
      - Length: { min: 6 }
